AllCops:
  NewCops: enable
  SuggestExtensions: false

Naming/FileName:
  Exclude:
    - 'lib/jekyll-database-tables.rb'

Style/Documentation:
  Exclude:
    - 'test/**/*'
    - 'lib/jekyll-database-tables.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 20
